using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace server.Utilities
{
    public static class SuccessMessage
    {
        public const string SIGN_IN_SUCCESSFULLY = "SIGN_IN_SUCCESSFULLY";
        public const string SIGN_UP_SUCCESSFULLY = "SIGN_UP_SUCCESSFULLY";
        public const string REFRESH_TOKEN_SUCCESSFULLY = "REFRESH_TOKEN_SUCCESSFULLY";
        public const string DEACTIVATE_ACCOUNT_SUCCESSFULLY = "DEACTIVATE_ACCOUNT_SUCCESSFULLY";
        public const string REACTIVATE_ACCOUNT_SUCCESSFULLY = "REACTIVATE_ACCOUNT_SUCCESSFULLY";
        public const string RESET_PASSWORD_EMAIL_SENT = "RESET_PASSWORD_EMAIL_SENT";
        public const string GOOGLE_AUTH_SUCCESSFULLY = "GOOGLE_AUTH_SUCCESSFULLY";
        public const string RESET_PASSWORD_SUCCESSFULLY = "RESET_PASSWORD_SUCCESSFULLY";
        public const string CHANGE_PASSWORD_SUCCESSFULLY = "CHANGE_PASSWORD_SUCCESSFULLY";
        public const string MAKE_RESERVATION_SUCCESSFULLY = "MAKE_RESERVATION_SUCCESSFULLY";
        public const string UPDATE_BOOKING_SUCCESSFULLY = "UPDATE_BOOKING_SUCCESSFULLY";
        public const string PAYMENT_TRACKED_SUCCESSFULLY = "PAYMENT_TRACKED_SUCCESSFULLY";
        public const string BOOK_SERVICE_SUCCESSFULLY = "BOOK_SERVICE_SUCCESSFULLY";
        public const string UPDATE_BOOKING_SERVICE_SUCCESSFULLY = "UPDATE_BOOKING_SERVICE_SUCCESSFULLY";
        public const string CREATE_ROOM_SUCCESSFULLY = "CREATE_ROOM_SUCCESSFULLY";
        public const string UPDATE_ROOM_SUCCESSFULLY = "UPDATE_ROOM_SUCCESSFULLY";
        public const string DELETE_ROOM_SUCCESSFULLY = "DELETE_ROOM_SUCCESSFULLY";
        public const string UPLOAD_IMAGE_SUCCESSFULLY = "UPLOAD_IMAGE_SUCCESSFULLY";
        public const string DELETE_IMAGE_SUCCESSFULLY = "DELETE_IMAGE_SUCCESSFULLY";
        public const string UPDATE_FEATURE_SUCCESSFULLY = "UPDATE_FEATURE_SUCCESSFULLY";
        public const string UPDATE_USER_SUCCESSFULLY = "UPDATE_USER_SUCCESSFULLY";
        public const string CREATE_ADMIN_SUCCESSFULLY = "CREATE_ADMIN_SUCCESSFULLY";
        public const string CREATE_FEATURE_SUCCESSFULLY = "CREATE_FEATURE_SUCCESSFULLY";
        public const string DELETE_FEATURE_SUCCESSFULLY = "DELETE_FEATURE_SUCCESSFULLY";
        public const string CREATE_ROOM_CLASS_SUCCESSFULLY = "CREATE_ROOM_CLASS_SUCCESSFULLY";
        public const string UPDATE_ROOM_CLASS_SUCCESSFULLY = "UPDATE_ROOM_CLASS_SUCCESSFULLY";
        public const string DELETE_ROOM_CLASS_SUCCESSFULLY = "DELETE_ROOM_CLASS_SUCCESSFULLY";
        public const string CREATE_FLOOR_SUCCESSFULLY = "CREATE_FLOOR_SUCCESSFULLY";
        public const string UPDATE_FLOOR_SUCCESSFULLY = "UPDATE_FLOOR_SUCCESSFULLY";
        public const string DELETE_FLOOR_SUCCESSFULLY = "DELETE_FLOOR_SUCCESSFULLY";
        public const string CREATE_SERVICE_SUCCESSFULLY = "CREATE_SERVICE_SUCCESSFULLY";
        public const string UPDATE_SERVICE_SUCCESSFULLY = "UPDATE_SERVICE_SUCCESSFULLY";
        public const string DELETE_SERVICE_SUCCESSFULLY = "DELETE_SERVICE_SUCCESSFULLY";
    }
}
